enum FilterSortBy {
  CHEAP_TO_EXPENSIVE = 'CHEAP_TO_EXPENSIVE',
  EXPENSIVE_TO_CHEAP = 'EXPENSIVE_TO_CHEAP',
  NEW_TO_OLD = 'NEW_TO_OLD',
  OLD_TO_NEW = 'OLD_TO_NEW',
  MOST_VIEWS = 'MOST_VIEWS ',
  LEAST_VIEWS = 'LEAST_VIEWS',
}

export { FilterSortBy };
