import {
  faBell,
  faCircleQuestion,
  faCommentDots,
  faEnvelope,
  faStar,
  faUser,
} from '@fortawesome/free-regular-svg-icons';
import {
  faAngleDown,
  faAngleUp,
  faAngleLeft,
  faAngleRight,
  faEye,
  faEyeSlash,
  faCheck,
  faList,
  faGear,
  faArrowRightFromBracket,
  faCamera,
  faPhone,
  faUserShield,
  faStopwatch,
} from '@fortawesome/free-solid-svg-icons';

export enum IconName {
  ANGLE_DOWN = 'angle-down',
  ANGLE_UP = 'angle-up',
  ANGLE_LEFT = 'angle-left',
  ANGLE_RIGHT = 'angle-right',
  EYE = 'eye',
  EYE_SLASH = 'eye-slash',
  CHECK = 'check',
  STAR = 'star',
  BELL = 'bell',
  USER = 'user',
  LIST = 'list',
  SETTINGS = 'gear',
  MESSAGE = 'comment-dots',
  SUPPORT = 'circle-question',
  SIGN_OUT = 'arrow-right-from-bracket',
  CAMERA = 'camera',
  PHONE = 'phone',
  EMAIL = 'envelope',
  PRIVACY_POLICY = 'user-shield',
  STOPWATCH = 'stopwatch',
}

export const IconNameToSvgIcon = {
  [IconName.ANGLE_DOWN]: faAngleDown,
  [IconName.ANGLE_UP]: faAngleUp,
  [IconName.ANGLE_LEFT]: faAngleLeft,
  [IconName.ANGLE_RIGHT]: faAngleRight,
  [IconName.EYE]: faEye,
  [IconName.EYE_SLASH]: faEyeSlash,
  [IconName.CHECK]: faCheck,
  [IconName.STAR]: faStar,
  [IconName.BELL]: faBell,
  [IconName.USER]: faUser,
  [IconName.LIST]: faList,
  [IconName.SETTINGS]: faGear,
  [IconName.MESSAGE]: faCommentDots,
  [IconName.SUPPORT]: faCircleQuestion,
  [IconName.SIGN_OUT]: faArrowRightFromBracket,
  [IconName.CAMERA]: faCamera,
  [IconName.PHONE]: faPhone,
  [IconName.EMAIL]: faEnvelope,
  [IconName.PRIVACY_POLICY]: faUserShield,
  [IconName.STOPWATCH]: faStopwatch,
};
