export enum UserPersonalInfoValidationMessage {
  FIRSTNAME_REQUIRED = 'FIRSTNAME_REQUIRED',
  FIRSTNAME_MIN = 'FIRSTNAME_MIN',
  FIRSTNAME_MAX = 'FIRSTNAME_MAX',
  LASTNAME_REQUIRED = 'LASTNAME_REQUIRED',
  LASTNAME_MIN = 'LASTNAME_MIN',
  LASTNAME_MAX = 'LASTNAME_MAX',

  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  EMAIL_PATTERN = 'EMAIL_PATTERN',
  PHONE_REQUIRED = 'PHONE_REQUIRED',
  PHONE_PATTERN = 'PHONE_PATTERN',

  WRONG_PASSWORD = 'WRONG_PASSWORD',
  EMPTY_PASSWORD = 'EMPTY_PASSWORD',
  NEW_PASSWORD = 'NEW_PASSWORD',
  SPACES_IN_PASSWORD = 'SPACES_IN_PASSWORD',
  DIFFERENT_PASSWORDS = 'DIFFERENT_PASSWORDS',
  SAME_PASSWORD = 'SAME_PASSWORD',
}
