export enum ValidationRanges {
  MIN_NAME_SYMBOLS = 1,
  MAX_NAME_SYMBOLS = 40,
  MAX_SOCIAL_NETWORK_URI_SYMBOLS = 150,
  MIN_PASSWORD_SYMBOLS = 8,
  MAX_PASSWORD_SYMBOLS = 16,
  MAX_TITLE_SYMBOLS = 50,
  MAX_DESCRIPTION_SYMBOLS = 6000,
}
