export { IS_ANDROID, IS_IOS } from './platform';
export {
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MAX_COUNTRY_LENGTH,
  MAX_REGION_LENGTH,
  MAX_CITY_LENGTH,
  MAX_DELIVERY_DATA_LENGTH,
  MAX_SOCIAL_NETWORK_LENGTH,
} from './validation';
export * from './images';
export { ENGLISH_LOCALE } from './day-js';
export {
  MILLISECOND_IN_MINUTE,
  UPDATE_END_DATE_INTERVAL_MILLISECONDS,
} from './time';
export {
  ANDROID_PN_ICON_NAME,
  ANDROID_PN_DEFAULT_CHANNEL_ID,
  CHANEL_NAME,
} from './push';
export { MINIMUM_SLIDER_PRICE, MAXIMUM_SLIDER_PRICE } from './slider-price';
