const MILLISECOND_IN_MINUTE = 60000;
const UPDATE_END_DATE_INTERVAL_MILLISECONDS = 1000;
const MINUTES_IN_HOUR = 60;

export {
  UPDATE_END_DATE_INTERVAL_MILLISECONDS,
  MILLISECOND_IN_MINUTE,
  MINUTES_IN_HOUR,
};
