const MIN_PASSWORD_LENGTH = 8;
const MAX_PASSWORD_LENGTH = 16;

const MIN_NAME_LENGTH = 1;
const MAX_NAME_LENGTH = 40;

const MAX_COUNTRY_LENGTH = 60;
const MAX_REGION_LENGTH = 30;
const MAX_CITY_LENGTH = 30;
const MAX_DELIVERY_DATA_LENGTH = 256;
const MAX_SOCIAL_NETWORK_LENGTH = 200;

export {
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MAX_COUNTRY_LENGTH,
  MAX_REGION_LENGTH,
  MAX_CITY_LENGTH,
  MAX_DELIVERY_DATA_LENGTH,
  MAX_SOCIAL_NETWORK_LENGTH,
};
