version: '3.8'
services:
  vsebude_db:
    container_name: vsebude_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vsebude_db
    ports:
      - '5432:5432'
    volumes:
      - vsebude_pg_data:/var/lib/postgresql/data/

  vsebude_adminer:
    container_name: vsebude_adminer
    image: adminer
    restart: always
    ports:
      - "3030:8080"
    depends_on:
      - vsebude_db

volumes:
  vsebude_pg_data:
