enum RootScreenName {
  SIGN_UP = 'Sign Up',
  SIGN_IN = 'Sign In',
  FORGOT_PASSWORD = 'Forgot Password',
  MAIN = 'Main',
  PERSONAL_INFO = 'Personal Info',
  SETTINGS = 'Settings',
  MESSAGES = 'Messages',
  SUPPORT = 'Support',
  WELCOME = 'Welcome',
  VERIFY_PHONE = 'Verify phone',
  VERIFY_EMAIL = 'Verify email',
  VERIFY_CODE_PHONE = 'Verify code phone',
  VERIFIED_PHONE = 'Verified phone',
  VERIFY_CODE_EMAIL = 'Verify code email',
  VERIFIED_EMAIL = 'Verified email',
  NEW_ITEM = 'Make a post',
  ITEM_INFO = 'Product Info',
  TYPE_OF_NEW_POST = 'Type of post',
  NEW_AUCTION = 'Make an Auction Post',
  MAIN_WITH_MENU = 'Menu',
  FILTER = 'Filter',
  PRODUCTS = 'Products',
  MY_LIST = 'My list ',
}

export { RootScreenName };
