enum RootScreenName {
  MAIN_WITH_MENU = 'Menu',
  PERSONAL_INFO = 'Personal Info',
  SETTINGS = 'Settings',
  MESSAGES = 'Messages',
  SUPPORT = 'Support',
  WELCOME = 'Welcome',
  VERIFY_PHONE = 'Verify phone',
  VERIFY_CODE = 'Verify code',
  VERIFIED = 'Verified',
  NEW_ITEM = 'Make a post',
  ITEM_INFO = 'Product Info',
  TYPE_OF_NEW_POST = 'Type of post',
  NEW_AUCTION = 'Make an Auction Post',
  SIGN_UP = 'Sign Up',
  SIGN_IN = 'Sign In',
  FORGOT_PASSWORD = 'Forgot Password',
  MAIN = 'Main',
  FAVORITE = 'Favorite',
  MY_LIST = 'My list',
  ACCOUNT_ROOT = 'Account',
  WELCOME_ROOT = 'Welcome root',
}

export { RootScreenName };
