export enum ProductActions {
  FETCH_PRODUCT = 'product/fetch-product',
  FETCH_PRODUCTS = 'product/fetch-products',
  FETCH_SIMILAR_PRODUCTS = 'product/fetch-similar-products',
  INCREMENT_PRODUCT_VIEWS = 'product/fetch-increment-product-views',
  ADD_PRODUCT_TO_FAVORITES = 'product/add-to-favorites',
  DELETE_PRODUCT_FROM_FAVORITES = 'product/delete-from-favorites',
  GET_FAVORITE_PRODUCT_IDS = 'product/get-favorite-ids',
  PLACE_BID = 'product/place-bid',
  UPDATE_CURRENT_ITEM_PRICE = 'product/update-current-item-price',
  AUCTION_PERMISSIONS = 'product/auction-permissions',
  AUCTION_LEAVE = 'product/auction-leave',
  GET_CURRENT_PRODUCT = 'product/fetch-current-product',
  SEARCH = 'product/search',
  CLEAR_SEARCH = 'product/clear-search',
}
