const images = {
  logo_small: require('~/assets/images/logo_small.png'),
  stamp: require('~/assets/images/stamp.jpg'),
  verify_phone: require('~/assets/images/verify-phone.png'),
  verification_code: require('~/assets/images/verification-code.png'),
  verified: require('~/assets/images/verified.png'),
  prytula: require('~/assets/images/organizations/prytula.png'),
  come_back_alive: require('~/assets/images/organizations/come-back-alive.png'),
  help_children: require('~/assets/images/organizations/help-children.png'),
  ihf: require('~/assets/images/organizations/ihf.png'),
  ico: require('~/assets/images/organizations/ico.png'),
  hospitallers: require('~/assets/images/organizations/hospitallers.png'),
  chooseTypeThumb: require('~/assets/images/choose-type.png'),
  list_item_image: require('~/assets/images/list-item-image.png'),
  list_item_avatar: require('~/assets/images/list-item-avatar.png'),
  list_item_organization: require('~/assets/images/list-item-organization.png'),
  no_image_available: require('./no-image-available.png'),
  ALCOHOLIC_BEVERAGES_AND_PRODUCTS: require('./categories/ALCOHOLIC_BEVERAGES_AND_PRODUCTS.png'),
  BEAUTY_AND_HEALTH: require('./categories/BEAUTY_AND_HEALTH.png'),
  CLOTHES_SHOES_AND_JEWELRY: require('./categories/CLOTHES_SHOES_AND_JEWELRY.png'),
  COTTAGE_GARDEN_AND_VEGETABLE_GARDEN: require('./categories/COTTAGE_GARDEN_AND_VEGETABLE_GARDEN.png'),
  GOODS_FOR_GAMERS: require('./categories/GOODS_FOR_GAMERS.png'),
  HOME_GOODS: require('./categories/HOME_GOODS.png'),
  LAPTOPS_AND_PC: require('./categories/LAPTOPS_AND_PC.png'),
  OFFICE_SCHOOL_BOOKS: require('./categories/OFFICE_SCHOOL_BOOKS.png'),
  PET_PRODUCTS: require('./categories/PET_PRODUCTS.png'),
  PLUMBING_AND_REPAIR: require('./categories/PLUMBING_AND_REPAIR.png'),
  SERVICES: require('./categories/SERVICES.png'),
  SMARTPHONES_TV_AND_ELECTRONICS: require('./categories/SMARTPHONES_TV_AND_ELECTRONICS.png'),
  SPORTS_AND_HOBBY: require('./categories/SPORTS_AND_HOBBY.png'),
  TOOLS_AND_AUTO_GOODS: require('./categories/TOOLS_AND_AUTO_GOODS.png'),
  APPLIANCES: require('./categories/appliances.png'),
  TOYS: require('./categories/toys.png'),
};
export { images };
