name: Release

on:
  push:
    branches: ['main']

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    environment:
      name: Release
      url: http://vse-bude.com.ua
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set deployment status to [in_progress]
        id: set_state_in_progress
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          run_id: ${{ github.run_id }}
          status: in_progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy frontend and backend. Migrate DB.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAIN_SERVER_HOST }}
          username: ${{ secrets.MAIN_SERVER_USERNAME }}
          password: ${{ secrets.MAIN_SERVER_PASSWORD }}
          port: ${{ secrets.MAIN_SERVER_PORT }}
          script_stop: true
          script: |
            whoami
            cd /home/ubuntu/vse-bude/
            pwd
            ls -a
            git reset --hard
            git fetch
            git checkout main
            git pull -f
            git status
            ./scripts/deploy.sh
      - name: Check app deployed successfully
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://vse-bude.com.ua|http://vse-bude.com.ua/api/health/
          max-attempts: 5
          retry-delay: 10s
      - name: Set deployment status
        id: set_state_final
        if: always()
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          status: ${{ job.status }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
