name: Release

on:
  workflow_run:
    workflows: ['Lint and build']
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    environment:
      name: Release
      url: http://vse-bude.com.ua
    steps:
      - name: Deploy frontend and backend. Migrate DB.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAIN_SERVER_HOST }}
          username: ${{ secrets.MAIN_SERVER_USERNAME }}
          password: ${{ secrets.MAIN_SERVER_PASSWORD }}
          port: ${{ secrets.MAIN_SERVER_PORT }}
          script_stop: true
          script: |
            whoami
            cd /home/ubuntu/vse-bude/
            pwd
            ls -a
            git reset --hard
            git fetch
            git checkout main
            git pull -f
            git status
            ./scripts/deploy.sh
      - name: Check app deployed successfully
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://vse-bude.com.ua|https://vse-bude.com.ua/api/health/
          max-attempts: 5
          retry-delay: 10s
